# Generated by Django 4.2.11 on 2024-03-20 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
