# Generated by Django 4.2.11 on 2024-03-20 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
