version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      DATABASE_NAME: airline
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 27017
    command: >
      sh -c "/wait-for-it.sh db 27017 -- &&
             python myproject/manage.py makemigrations myapp &&
             python myproject/manage.py migrate &&
             python myproject/manage.py loaddata myapp/initial_data.json &&
             python myproject/manage.py runserver 0.0.0.0:8000"
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: airline
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
