version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
    command: ["./wait-for-it.sh", "db:27017", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  mongo_data:
    driver: local
