version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: airline
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    command: >
      sh -c "/wait-for-it.sh db 3306 -- &&
             python myproject/manage.py makemigrations myapp &&
             python myproject/manage.py migrate &&
             python myproject/manage.py loaddata myproject/myapp/initial_data.json &&
             python myproject/manage.py runserver 0.0.0.0:8000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: airline
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
